services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: learning_app
    volumes:
      - ./backend:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./storage:/app/storage
    environment:
      PHP_MEMORY_LIMIT: "512M"
    depends_on:
      - db
    networks:
      - blognet

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: learning_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app
    networks:
      - blognet

  db:
    image: mysql:8.0
    container_name: learning_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - blognet

  frontend:
    image: node:20-alpine
    container_name: learning_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    networks:
      - blognet

volumes:
  dbdata:
  node_modules:

networks:
  blognet:
    driver: bridge  # Add this line